<a href="https://colab.research.google.com/github/danielrosetti07/Trabalhos-Faculdade/blob/main/Trabalho_Apriori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Trabalho realizado por: Daniel Rosetti da Rocha Ribeiro e Douglas Rosetti da Rocha Ribeiro

# **O que é o algoritmo Apriori?**

O algoritmo Apriori é um algoritmo de aprendizado de máquina não supervisionado
utilizado no aprendizado de regras de associação. Aprendizado de regras de
associação é uma técnica de mineração de dados que identifica padrões, conexões e dependências frequentes entre diversos grupos de itens chamados conjuntos de itens nos dados. Alguns casos de uso comuns são sistemas de previsão e recomendação, como análise de cestas de mercado para plataformas de comércio eletrônico.

Foi criado por  Rakesh Agrawal e Ramakrishnan Srikant em 1994, é utilizado para encontrar conjuntos de itens frequente que aparecem em um conjunto de dados.
Ele funciona analisando combinações de itens passo a passo (1 item, depois 2, depois 3...), usando a ideia de que:               
* Se um grupo de itens é frequente, todos os seus subconjuntos também são.  
* Se um grupo não é frequente, nenhum conjunto maior com ele será.

É muito usado em análise de compras (ex: recomendar meias para quem compra sapatos).

☑ Vantagens:
* Fácil de entender
* Fácil de aplicar em diferentes áreas

⚠ Desvantagens:
* Pode ser lento e consumir muita memória com muitos dados  

Por isso é recomendado utilizar com outras técnicas

A função Apriori é integrada a muitas linguagens de programação populares, inclusive Python, Java e R, facilitando a integração de regras de associação de qualidade junto com conjuntos de itens frequentes em aplicativos ou sistemas existentes.

# **Como  funciona o algoritmo Apriori**

O algoritmo Apriori funciona em etapas para encontrar grupos de itens frequentes e criar regras de associação:

1. Geração de conjuntos de itens frequentes:  
Identifica itens individuais e combinações que aparecem com frequência eliminando os que não aparecem com frequência.
2. Expansão e posterior poda de conjuntos de itens:  
Combina itens frequentes para formar grupos maiores e remove combinações pouco frequentes, reduzindo o trabalho.
3. Repetição da etapa 1 e 2:  
Repete esse processo até encontrar todos os conjuntos de itens relevantes.

No final, o algoritmo analisa esses conjuntos para descobrir relações fortes entre os itens.

# **Medição dos conjuntos de itens**



#   Support:

    É definido como a frequência que um item aparece no conjunto de itens.
    
    Support {X} = número de vezes que X aparece / quantidade total de itens.

    Essa métrica, portanto, define a probabilidade de ocorrência de cada item individual nas transações.
    A mesma lógica pode ser estendida aos conjuntos de itens.

#    Confidence:
    
    Identifica a probabilidade de itens ou conjuntos de itens ocorrerem juntos nos conjuntos de itens.

    Confidence {X -> Y} = número de vezes que X e Y aparecem / número de vezes que X aparece.

    Ela representa a probabilidade de que os itens em Y sejam comprados quando os itens em X são comprados.

    
#    Lift:

    É o fator que indica o quanto a probabilidade do item *X* levar ao item *Y* é maior do que a probabilidade isolada de *X* ocorrer.

    Lift {X -> Y} = Support {X, Y} / Support {X} * Support {Y}

    Lift > 1: associação positiva (itens comprados juntos com mais frequência)
    Lift = 1: coincidência
    Lift < 1: associação negativa (itens comprados juntos com menos frequência)

# **Aplicando o algoritmo**

In [ ]:
import warnings
warnings.filterwarnings('ignore')

# Importando as bibliotecas pandas para manipulação de dados e as funções 'apriori' e 'association_rules'
# do mlxtend para o algoritmo.

import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

# Definindo um dicionário chamado data, que representa cinco transações de compras, onde cada chave é um produto
# e os valores (1 e 0) indicam se o produto foi comprado ou não.

data = {
    'Leite': [1, 1, 1, 0, 1, 1, 0],
    'Pão': [1, 0, 1, 1, 0, 1, 1],
    'Manteiga': [0, 1, 0, 1, 0, 1, 0],
    'Ovo': [1, 0, 0, 1, 1, 0, 1],
    'Cerveja': [0, 1, 1, 1, 1, 1, 1]
}

# Convertendo o dicionário em um DataFrame do Pandas chamado df, formato ideal para as próximas etapas

df = pd.DataFrame(data)

In [ ]:
# O 'df' agora está no formato de uma planilha

df

   Leite  Pão  Manteiga  Ovo  Cerveja
0      1    1         0    1        0
1      1    0         1    0        1
2      1    1         0    0        1
3      0    1         1    1        1
4      1    0         0    1        1
5      1    1         1    0        1
6      0    1         0    1        1

In [ ]:
# Como ficou o support de cada item de maneira individual

itens_individuais = frequent_itemsets[frequent_itemsets['itemsets'].apply(lambda x: len(x) == 1)]
itens_individuais

    support    itemsets
0  0.714286     (Leite)
1  0.714286       (Pão)
2  0.428571  (Manteiga)
3  0.571429       (Ovo)
4  0.857143   (Cerveja)

In [ ]:
# Encontra grupos de produtos que são comprados juntos com frequência, ignorando os que aparecem pouco.

frequent_itemsets = apriori(df, min_support=0.4, use_colnames=True)

# Encontra grupos de produtos que são comprados juntos com frequência, ignorando os que aparecem pouco.

rules = association_rules(frequent_itemsets, metric='confidence', min_threshold= 0.6)

# Mostra as regras mais importantes, seus percentuais de aparição (support), confiabilidade (confidence) e se a associação é mais do que aleatória (lift).

print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])

  antecedents consequents   support  confidence      lift
0     (Leite)       (Pão)  0.428571    0.600000  0.840000
1       (Pão)     (Leite)  0.428571    0.600000  0.840000
2   (Cerveja)     (Leite)  0.571429    0.666667  0.933333
3     (Leite)   (Cerveja)  0.571429    0.800000  0.933333
4       (Ovo)       (Pão)  0.428571    0.750000  1.050000
5       (Pão)       (Ovo)  0.428571    0.600000  1.050000
6   (Cerveja)       (Pão)  0.571429    0.666667  0.933333
7       (Pão)   (Cerveja)  0.571429    0.800000  0.933333
8  (Manteiga)   (Cerveja)  0.428571    1.000000  1.166667
9       (Ovo)   (Cerveja)  0.428571    0.750000  0.875000

* Os valores de support (0,4 a 0,6) indicam que estas associações aparecem em 40-60% de todas as transações.

* As pontuações de confidence (0,6 a 1,0) mostram a confiabilidade das regras, sendo algumas como Manteiga --> Cerveja serão (100% de confiança).

* Os valores de lift (~0.8 a 1,1) sugerem associações moderadas, mas significativas, indicando que estes pares de itens ocorrem juntos com um pouco mais de frequência do que o acaso.

# Exemplo de como pode ser aplicado

In [ ]:
from IPython.display import Image
Image(url='https://www.researchgate.net/profile/Tohari-Ahmad/publication/280805918/figure/fig2/AS:391471560708112@1470345501554/The-Proposed-Method-for-Fraud-Detection.png')

A imagem mostra um processo de detecção de fraude usando regras de associação.
* O sistema analisa dados e descobre padrões suspeitos automaticamente.

1. Dados de treinamento
    * Começa com um conjunto de dados (Training Data Set)
    * Exemplo: registros de compras, transações, eventos

2. Filtragem
    * Os dados são filtrados (Filtering Event Log)
    * Remove o que não é relevante

3. Análises principais
* O sistema analisa os dados de várias formas:

    * Fluxo de atividades (Control Flow)
    * Uso de recursos (Resource Analysis)
    * Tempo de execução (Throughput Time)
    * Pontos de decisão (Decision Point)

  Isso ajuda a encontrar comportamentos fora do padrão

4. Identificação de comportamento suspeito
    * Junta tudo e identifica Fraudulent Behavior (comportamento fraudulento)

5. Aplicação do Apriori

* Aqui entra o principal:

    * O sistema usa o método Apriori
    * Ele gera regras de associação

  Exemplo: “SE cliente compra X e Y → alta chance de fraude”

6. Verificação por especialista
    * Um humano valida as regras (Expert Verification)

7. Teste e checagem
    * Usa outro conjunto de dados (Testing Data Set)
    * Faz uma verificação de conformidade (Compliance Check)

8. Regras finais

  * As regras são separadas em:

    * Fraud Rules → regras de fraude
    * Legal Rules → regras normais

9. Resultado final
    * O sistema decide se algo é fraude (Fraudulent Status)
    * E pode adicionar novas regras ao sistema

Onde entra o Apriori?
* Ele é usado para:

    * Descobrir padrões frequentes
    * Criar regras do tipo “SE… ENTÃO…”
    * Ajudar a identificar comportamentos suspeitos automaticamente

# Referências Bibliográficas

* DERRICK MWITI. Apriori Algorithm Explained: A Step-by-Step Guide with Python Implementation. *Datacamp*, 2025. Disponivel em: https://www.datacamp.com/pt/tutorial/apriori-algorithm. Acesso em: 04 de Abril de 2026

* JOSHUA NOBLE. O que é o algoritmo Apriori?. *IBM*, 2024. Disponivel em: https://www.ibm.com/br-pt/think/topics/apriori-algorithm#2014952963. Acesso em: 04 de Abril de 2026